FROM codenvy/shellinabox

RUN sudo apt-get update -y && \
    sudo apt-get install --no-install-recommends -y -q build-essential python2.7 python2.7-dev python-pip git && \
    sudo pip install -U pip && \
    sudo pip install virtualenv