#!/bin/bash

#
# CODENVY CONFIDENTIAL
# __________________
#
#  [2012] - [2015] Codenvy, S.A.
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Codenvy S.A. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Codenvy S.A.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Codenvy S.A..
#
# Run this script with first parameter --install to install it into the system.
# Then open new terminal window to use it

# $1 - file name to find full path of parent folder for
getFullPathOfParentFolderForFile() {
    echo "$(cd $(dirname ${1}) && pwd -P)"
}

cbuildRun() {
    if [ "${1}" == '--install' ]; then
        if [[ -z "${PATH_TO_CBUILD_PROJECTS_FOLDER}"  || ${2} == '--f' ]]; then
            local cbuildPredictedProjectsFolderPath=$(dirname $(dirname $(getFullPathOfParentFolderForFile "$0")))
            read -e -i "${cbuildPredictedProjectsFolderPath}" -p "Set projects folder: " pathToProjectsFolder
            if [[ ${pathToProjectsFolder} == */ ]]; then
                pathToProjectsFolder=${pathToProjectsFolder:0:-1}
            fi
            echo -e "\nexport PATH_TO_CBUILD_PROJECTS_FOLDER=${pathToProjectsFolder}\n" >> ~/.bashrc
            export PATH_TO_CBUILD_PROJECTS_FOLDER=${pathToProjectsFolder}
        fi

        # install cbuild script to use it from anywhere in the system
        # and enable autocompletion
        if [[ -z "${PATH_TO_CBUILD_LIBRARY_FOLDER}" || ${2} == '--f' ]]; then
            local cbuildFolderPath=$(getFullPathOfParentFolderForFile "$0")
            echo -e "\nexport PATH_TO_CBUILD_LIBRARY_FOLDER=${cbuildFolderPath}\n" >> ~/.bashrc
            export PATH_TO_CBUILD_LIBRARY_FOLDER=${cbuildFolderPath}
        fi
        sudo rm -f /usr/bin/cbuild /etc/bash_completion.d/cbuild_autocompletion
        sudo ln -s ${PATH_TO_CBUILD_LIBRARY_FOLDER}/cbuild /usr/bin/cbuild
        sudo ln -s ${PATH_TO_CBUILD_LIBRARY_FOLDER}/cbuild_autocompletion /etc/bash_completion.d/cbuild_autocompletion
    else
        # workarounds for cbuild usage without installation
        if [[ -z "${PATH_TO_CBUILD_LIBRARY_FOLDER}" ]]; then
            export PATH_TO_CBUILD_LIBRARY_FOLDER=$(getFullPathOfParentFolderForFile "$0")
        fi
        if [[ -z "${PATH_TO_CBUILD_PROJECTS_FOLDER}" ]]; then
            export PATH_TO_CBUILD_PROJECTS_FOLDER=$(dirname $(dirname $(getFullPathOfParentFolderForFile "$0")))
        fi

        # To use custom build script set variable PATH_TO_CUSTOM_CBUILD_LIBRARY as path to your script
        if [[ ! -z "${PATH_TO_CUSTOM_CBUILD_LIBRARY}" ]]; then
            source "${PATH_TO_CUSTOM_CBUILD_LIBRARY}"
        else
            source ${PATH_TO_CBUILD_LIBRARY_FOLDER}/buildLibrary.sh
        fi

        run "$@"
    fi
}

set -e

cbuildRun "$@"
